version: '3'
services:

  dsw_server:
    image: datastewardshipwizard/wizard-server:2.7.0
    restart: always
    hostname: dsw_server
    depends_on:
      - rabbitmq
      - mongo
    volumes:
      - ./dsw-server/application.yml:/application/engine-wizard/config/application.yml:ro
      - ./dsw-server/integration.yml:/application/engine-wizard/config/integration.yml:ro
    ports:
      - 3000:3000

  dsw_client:
    image: datastewardshipwizard/wizard-client:2.7.0
    restart: always
    hostname: dsw_client
    environment:
    # (!) Change API_URL
    # API_URL: <dsw-url>
      API_URL: http://localhost:3000
    volumes:
      - ./dsw-client/variables.scss:/src/scss/customizations/_variables.scss:ro
      - ./dsw-client/assets:/usr/share/nginx/html/assets:ro
      - ./dsw-client/configuration/provisioning.json:/configuration/provisioning.json:ro
      - ./dsw-client/favicon.ico:/usr/share/nginx/html/favicon.ico:ro
    ports:
      - 8080:80

  docworker:
    image: datastewardshipwizard/document-worker:2.7.0
    restart: always
    depends_on:
      - rabbitmq
    volumes:
      - ./docworker/config.yml:/app/config.yml:ro

  mongo:
    image: mongo:4.2.3
    restart: always
    # (!) Expose only for debugging locally or set-up authentication
    ports:
      - 27017:27017
    # command: mongod --auth
    environment:
      MONGO_INITDB_DATABASE: wizard
    #   MONGO_INITDB_ROOT_USERNAME: admin
    #   MONGO_INITDB_ROOT_PASSWORD: secure-password
    volumes:
      - mongo-data:/data/db
    # OR
    # - ./mongo/data:/data/db
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  rabbitmq:
    image: rabbitmq:3.8.2-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  agraph:
    # TODO: secured port with certs?
    image: franzinc/agraph:v7.0.1
    restart: always
    ports:
      - 10000-10035:10000-10035
    hostname: agraph
    shm_size: '1gb'
    volumes:
      - agraph-data:/agraph/data
    # OR
    #  - ./allegrograph/data:/agraph/data/
      - ./allegrograph/agraph.cfg:/agraph/etc/agraph.cfg

  submission_service:
    image: datastewardshipwizard/triple-store-submission-service:1.2.0
    restart: always
    hostname: submission_service
    volumes:
      - ./submission-service/config.yml:/app/config.yml:ro

  proxy:
    image: nginx:1.17
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/nginx:/etc/nginx:ro
      - ./proxy/letsencrypt:/var/www/letsencrypt:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  mongo-data:
  agraph-data:
